Tower hardware simulations
UCSD-E4E/rct_tower_system_hardware pull request #3
Opened 2023-11-03 21:11 UTC by vbogdev

Set simulations to correct time, added fact that 12 AWG wire is to be used, updated voltage chart for lead acid battery, added summary of other battery types.

2023-11-08 18:21 UTC, ntlhui requested changes

2023-11-08 18:21 UTC, ntlhui commented on tower_battery/simulations/simulations_report.md
> + - LiNiMnCoO2:Does not have both high energy storage and high energy output, might be difficult to find a good fitting battery of this kind.
Do you have sources/numbers to cite for these?

2023-11-08 20:19 UTC, vbogdev commented on tower_battery/simulations/simulations_report.md
> + - LiNiMnCoO2:Does not have both high energy storage and high energy output, might be difficult to find a good fitting battery of this kind.
Found a new table that was much more informative than my previous source and added links to table in document. NiCds would also probably work pretty well, especially for their cost, so I was wrong with what I said during the hardware standup from friday. Also updated simulations, inrush current issue was because of large timestep, actual jump in current is much more brief.

2023-12-25 22:51 UTC, ntlhui approved these changes

2023-12-25 22:51 UTC, merged